name: Build DLL

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSVC Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Download MinHook Source
      run: |
        git clone https://github.com/TsudaKageyu/minhook.git minhook

    - name: Compile CPP and MinHook to DLL
      run: |
        cl /LD /O2 QJ_EdiusHook.cpp minhook/src/buffer.c minhook/src/hook.c minhook/src/trampoline.c minhook/src/hde/hde64.c /I"minhook/include" /I"minhook/src" /link /OUT:QJ_EdiusHook.dll user32.lib kernel32.lib

    - name: Upload DLL Artifact
      uses: actions/upload-artifact@v4
      with:
        name: QJ_EdiusHook-DLL
        path: QJ_EdiusHook.dll
