name: Build DLL

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compile CPP to DLL using MinGW
      run: |
        g++ -shared -o QJ_EdiusHook.dll QJ_EdiusHook.cpp -luser32 -lkernel32

    - name: Upload DLL Artifact
      uses: actions/upload-artifact@v4
      with:
        name: QJ_EdiusHook-DLL
        path: QJ_EdiusHook.dll
